/**
 * Strict, zero-I/O wire contract between the DSH Host supervisor and a local
 * Desktop broker. Transport ownership and authorization policy live elsewhere.
 * @module @deepseek-ai/dsh-host-control-protocol
 */

export {
  HOST_CONTROL_MAX_FRAME_BYTES,
  HostControlProtocolError,
  decodeHostControlFrame,
  encodeHostControlFrame,
  encodeHostInspectSignaturePayload,
} from './codec.ts'
export type { HostControlProtocolFailure } from './codec.ts'
export { canonicalMigrationRecords, migrationProfileSelectorHash, migrationSemanticDigest } from './migration-canonical.ts'
export type { CanonicalMigrationRecord } from './migration-canonical.ts'
export type {
  HostControlCapability,
  HostControlClientInstanceId,
  HostControlCorrelationId,
  HostControlErrorCode,
  HostControlErrorFrame,
  HostControlFrame,
  HostControlJti,
  HostControlNonce,
  HostControlPublicKey,
  HostControlProtocolVersion,
  HostControlRequestId,
  HostControlSha256,
  HostControlSignature,
  HostAccountBindingHandle,
  HostAuthorityEnvironmentId,
  HostAuthorizedParams,
  HostProfileId,
  HostViewLeaseId,
  HostViewActivationHandle,
  HostInspectRequest,
  HostInspectResult,
  ProfileOpenRequest,
  ProfileOpenResult,
  ProfileViewActivateRequest,
  ProfileViewActivateResult,
  ProfileLeaseCloseRequest,
  ProfileLeaseCloseResult,
  ProfileStatusRequest,
  ProfileStatusResult,
  ProfileEnsureRequest,
  ProfileEnsureResult,
  ProfileRestoreRequest,
  ProfileRestoreResult,
  MigrationExportBeginRequest,
  MigrationExportBeginResult,
  MigrationExportInventoryRequest,
  MigrationExportInventoryResult,
  MigrationExportReadRequest,
  MigrationExportReadResult,
  MigrationExportRecord,
  HostMigrationTransferId,
  HostMigrationImportId,
  HostMigrationSourceAuthority,
  MigrationExistingSourceInventoryRequest,
  MigrationExistingSourceInventoryResult,
  MigrationImportStageRequest,
  MigrationImportStageResult,
  MigrationImportStatusRequest,
  MigrationImportStatusResult,
  MigrationImportVerifyRequest,
  MigrationImportVerifyResult,
  MigrationImportCommitRequest,
  MigrationImportCommitResult,
  MigrationImportAbortRequest,
  MigrationImportAbortResult,
  HostInstanceId,
  InstallationId,
} from './types.ts'
