import { defineConfig } from 'tsdown'
import { fileURLToPath } from 'node:url'
import { typertPlugin } from '../../typert/generator/lib/types/tsdown-plugin.js'

/** Build Host authority entries plus the standalone Main-only client artifact. */
export default defineConfig([
  {
    entry: { index: 'lib/types/index.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u, /^yaml(?:\/|$)/u],
    plugins: [typertPlugin({ mode: 'package', faces: ['host'] })],
  },
  {
    entry: { startup: 'lib/types/startup.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u, /^yaml(?:\/|$)/u],
    plugins: [typertPlugin({ mode: 'package', faces: ['host'] })],
  },
  {
    entry: { 'windows-startup': 'lib/types/windows-startup.js' },
    // The verified startup loads from a data URL; YAML's default ESM export avoids createRequire(import.meta.url).
    alias: { yaml: fileURLToPath(new URL('./node_modules/yaml/browser/index.js', import.meta.url)) },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u, /^yaml(?:\/|$)/u],
  },
  {
    entry: { 'windows-host-pipe-worker-entry': 'lib/types/windows-host-pipe-worker-entry.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u],
  },
  {
    entry: { 'windows-host-client-worker-entry': 'lib/types/windows-host-client-worker-entry.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u],
  },
  {
    entry: { 'windows-embedding-identity-entry': 'lib/types/windows-embedding-identity-entry.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    codeSplitting: false,
    noExternal: [/^@deepseek-ai\//u],
  },
  {
    entry: { 'host-control-client': 'lib/types/client.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    noExternal: [/^@deepseek-ai\/dsh-host-control-protocol(?:\/|$)/u],
    codeSplitting: false,
  },
])
