/** Machine-local authority for one Desktop-managed DSH Host. @module @deepseek-ai/dsh-desktop-host */

export { HostAuthorityError } from './types.ts'
export type * from './types.ts'
export { ProfileRegistry, personIndex } from './profile-registry.ts'
export { RestartingMigrationTarget } from './restarting-migration-target.ts'
export { MigrationOwnerStateApplicator, type AppliedMigrationOwnerState } from './migration-owner-state-applicator.ts'
export { MaterializedMigrationOwnerStateSource } from './materialized-migration-owner-state-source.ts'
export { createLegacyMigrationExportService } from './legacy-migration-source.ts'
export { SingleHostLock, acquireSingleHostLock } from './single-instance.ts'
export { ProfileWorkerSupervisor } from './worker-supervisor.ts'
export { ProfileWorkerProcessFactory } from './profile-worker-process.ts'
export type { ProfileWorkerProcessFactoryOptions } from './profile-worker-process.ts'
export { DshWebProfileWorkerFactory } from './dsh-web-profile-worker.ts'
export type { DshWebProfileWorkerFactoryOptions, ProfileListenerAttestor } from './dsh-web-profile-worker.ts'
export { createMacOSPeerAttestor } from './macos-peer-attestor.ts'
export type { MacOSPeerAttestorOptions, MacOSPeerBindings } from './macos-peer-attestor.ts'
export { FileHostJournal, SessionCommandAuthority } from './session-command.ts'
export { ApprovalAuthority } from './approval.ts'
export { ContextLeaseAuthority } from './context-lease.ts'
export { DesktopHost } from './desktop-host.ts'
export { HostRequestAuthorizer, UnixHostClient, UnixHostServer, discoverUnixHost } from './unix-transport.ts'
export type { MigrationExportService, UnixHostClientOptions, UnixHostDiscovery, UnixHostServerOptions, UnixPeerAttestor, UnixPeerEvidence } from './unix-transport.ts'
